import React from "react";
import { Link } from "react-router-dom";
import "./Footer.css";

function Footer() {
  return (
    <footer className="app-shell-footer bg-[#1B3A6B] text-white w-full border-t border-[#BFDBFE]">

      <div className="max-w-[1600px] mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">

        {/* Brand / Contact */}
        <div className="p-6 lg:p-7 lg:border-r border-white/20">
          <h2 className="text-lg sm:text-xl font-bold mb-4 tracking-wide text-white">
            FinAudit<span className="text-yellow-400">X</span>
          </h2>

          <div className="space-y-2 text-xs sm:text-sm text-blue-100">
            <p>
              <span className="font-semibold text-white">Phone:</span>{" "}
              +91 XXXXX XXXXX
            </p>

            <p>
              <span className="font-semibold text-white">Email:</span>{" "}
              info@finauditx.com
            </p>

            <p>
              <span className="font-semibold text-white">Location:</span>{" "}
              Pune, Maharashtra, India
            </p>
          </div>
        </div>

        {/* Important Links */}
        <div className="p-6 lg:p-7 lg:border-r border-white/20">
          <h2 className="text-xs sm:text-sm font-bold mb-4 text-white">
            Important Links
          </h2>

          <div className="flex flex-col space-y-2 text-xs sm:text-sm text-blue-100">
            <Link
              to="/"
              className="hover:text-orange-300 transition-colors w-fit font-medium"
            >
              Dashboard
            </Link>

            <Link
              to="/about"
              className="hover:text-orange-300 transition-colors w-fit font-medium"
            >
              About Us
            </Link>

            <Link
              to="/contact"
              className="hover:text-orange-300 transition-colors w-fit font-medium"
            >
              Contact Us
            </Link>
          </div>
        </div>

        {/* Visitor Count */}
        <div className="p-6 lg:p-7 lg:border-r border-white/20">
          <h2 className="text-xs sm:text-sm font-bold mb-4 text-white">
            Total Visitor Count
          </h2>

          <p className="text-xl sm:text-2xl font-bold text-orange-400 tabular-nums">
            000000
          </p>

          <p className="text-xs text-blue-200 mt-2">
            Prototype demonstration
          </p>
        </div>

        {/* Disclaimer */}
        <div className="p-6 lg:p-7">
          <h2 className="text-xs sm:text-sm font-bold mb-4 text-white">
            Disclaimer
          </h2>

          <p className="text-xs sm:text-sm leading-relaxed text-blue-100">
            FinAuditX provides digital audit and advisory support for
            informational and analytical purposes. The insights and
            recommendations generated by the platform should not be considered
            a substitute for professional financial, legal, or regulatory
            advice.
          </p>
        </div>

      </div>

      {/* Copyright */}
      <div className="border-t border-white/20 bg-[#0F2A52] text-center px-4 py-3 text-xs sm:text-sm text-blue-200 font-medium">
        © 2026 FinAudit<span className="text-yellow-400">X</span>. All Rights Reserved.
      </div>

    </footer>
  );
}

export default Footer;