import React from "react";
import { Mail, Phone, MapPin, Clock, Instagram, Facebook, Twitter, Linkedin, Info } from 'lucide-react';
function ContactUs() {
  const contactDetails = [
    {
      icon: Mail,
      title: "Email",
      value: "info@finauditx.com",
      description: "Send us an email anytime",
    },
    {
      icon: Phone,
      title: "Phone",
      value: "+91 XXXXX XXXXX",
      description: "Mon-Fri, 9AM - 6PM IST",
    },
    {
      icon: MapPin,
      title: "Location",
      value: "Pune, Maharashtra, India",
      description: "Our headquarters",
    },
    {
      icon: Clock,
      title: "Working Hours",
      value: "Monday to Friday",
      description: "9:00 AM - 6:00 PM IST",
    },
  ];

  const socialLinks = [
    { name: "Instagram", icon: Instagram },
    { name: "Facebook", icon: Facebook },
    { name: "X (Twitter)", icon: Twitter },
    { name: "LinkedIn", icon: Linkedin },
  ];
  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <h1 className="text-xl sm:text-2xl font-bold text-[#1B3A6B]">Contact Us</h1>
        <p className="text-[#4B6080] mt-1">
          Get in touch with the FinAuditX team for support and inquiries
        </p>
      </div>
      {/* Contact Info Card */}
      <div className="card">
        <h2 className="card-header">Get in Touch</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {contactDetails.map((detail) => {
            const Icon = detail.icon;
            return (
              <div key={detail.title} className="bg-white border border-[#BFDBFE] p-4">
                <div className="p-2 bg-[#EFF6FF] w-fit mb-3">
                  <Icon className="text-[#1D4ED8]" size={20} />
                </div>
                <div className="text-xs text-[#4B6080] uppercase tracking-wider font-semibold mb-1">{detail.title}</div>
                <div className="font-bold text-[#1B3A6B] text-xs sm:text-sm">{detail.value}</div>
                <div className="text-xs text-[#4B6080] mt-1">{detail.description}</div>
              </div>
            );
          })}
        </div>
      </div>
      {/* Social Media */}
      <div className="card">
        <h2 className="card-header">Connect With Us</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {socialLinks.map((platform) => {
            const Icon = platform.icon;
            return (
              <a
                key={platform.name}
                href="#"
                className="bg-white border border-[#BFDBFE] p-4 hover:border-[#16A34A] hover:bg-[#F0FDF4] transition-all cursor-pointer flex items-center gap-3"
              >
                <div className="p-2 bg-[#EFF6FF]">
                  <Icon className="text-[#1D4ED8]" size={20} />
                </div>
                <span className="font-bold text-xs sm:text-sm text-[#1B3A6B]">{platform.name}</span>
              </a>
            );
          })}
        </div>
      </div>

      {/* Disclaimer */}
      <div className="card bg-[#FFF7ED]/50 border-[#FED7AA]">
        <div className="flex items-start gap-3">
          <div className="p-2 bg-[#FFF7ED] flex-shrink-0 mt-0.5">
            <Info className="text-[#EA580C]" size={20} />
          </div>
          <div>
            <h2 className="text-xs sm:text-sm font-bold text-[#1B3A6B] mb-2">Disclaimer</h2>
            <p className="text-xs sm:text-sm text-[#1F3555] leading-relaxed">
              FinAuditX provides digital audit and advisory support for
              informational and analytical purposes. The insights and
              recommendations generated by the platform should not be considered
              a substitute for professional financial, legal, or regulatory
              advice.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
  

export default ContactUs;